# Generated by Django 4.1.3 on 2022-11-18 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('codigoPostal', models.CharField(db_column='codigo_postal', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='AlmacenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacioAnaquel', models.IntegerField(db_column='espacio_anaquel')),
                ('tipo', models.CharField(choices=[('A', 'SECO'), ('B', 'SEMI-SECO'), ('C', 'HUMEDO')], max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('departamento', models.OneToOneField(db_column='departamento_id', on_delete=django.db.models.deletion.CASCADE, to='gestion.departamentomodel')),
            ],
            options={
                'db_table': 'almacenes',
                'ordering': ['espacioAnaquel', 'direccion'],
                'unique_together': {('direccion', 'tipo')},
            },
        ),
    ]
