"""migracion inicial

Revision ID: 7d3d507b2904
Revises: 
Create Date: 2022-12-12 21:51:35.138716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3d507b2904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('id')
    )
    op.create_table('intercambios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('angel_id', sa.Integer(), nullable=False),
    sa.Column('ahijado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ahijado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['angel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ahijado_id'),
    sa.UniqueConstraint('angel_id')
    )
    op.create_table('regalos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regalos')
    op.drop_table('intercambios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
